## fetch_data.R -- download the two raw inputs the PACE notebooks need and place
## them at the paths the notebooks read from. Run from the repository root:
##
##   Rscript fetch_data.R
##
## The data are not stored in git (the two inputs total ~0.6 GB). Every PACE fit
## and competitor result is regenerated by the notebooks, so nothing else is
## fetched. There are two sources:
##
##   * Melanoma (CosMx) -- the public SIMVI Zenodo record 14708000 (Dong et al.,
##     CC BY 4.0). Fetched directly; no action needed.
##   * Breast cancer (Xenium) -- the derived SpatialExperiment (10x public data,
##     nucleus segmentation, scClassify cell-type annotation). Set BC_URL / BC_MD5
##     below to your own deposit; see ZENODO.md.

## ---- breast cancer SPE -- FILL THESE IN AFTER DEPOSITING --------------------
BC_URL <- "REPLACE_WITH_BC_DOWNLOAD_URL"   # direct download URL for the .rds
BC_MD5 <- "REPLACE_WITH_BC_MD5"            # md5sum of spe_10x_nuclei_withMetrics.rds

## ---- melanoma h5ad -- public SIMVI record (no action needed) ---------------
MEL_URL <- "https://zenodo.org/api/records/14708000/files/Melanoma_5612.h5ad/content"
MEL_MD5 <- "679da7c91a3563fc412eef5edbac851c"

## Where each file must land (relative to the repository root).
BC_DEST  <- "data/spe_10x_nuclei_withMetrics.rds"
MEL_DEST <- "data/simvi_melanoma/14708000/Melanoma_5612.h5ad"

## ---- download one file with md5 verification -------------------------------
download_verified <- function(url, dest, md5, label) {
  if (file.exists(dest) && identical(unname(tools::md5sum(dest)[[1]]), md5)) {
    message(label, ": already present and verified, skipping.")
    return(invisible())
  }
  dir.create(dirname(dest), showWarnings = FALSE, recursive = TRUE)
  message("Downloading ", label, " ...")
  utils::download.file(url, dest, mode = "wb")
  got <- unname(tools::md5sum(dest)[[1]])
  if (!identical(got, md5))
    stop(label, " md5 mismatch: expected ", md5, " got ", got, call. = FALSE)
  message(label, ": downloaded and md5 verified.")
}

## ---- fetch both inputs ------------------------------------------------------
if (BC_URL == "REPLACE_WITH_BC_DOWNLOAD_URL")
  stop("Set BC_URL (and BC_MD5) in fetch_data.R first -- the breast cancer SPE ",
       "must be deposited and its download URL filled in.", call. = FALSE)

download_verified(BC_URL,  BC_DEST,  BC_MD5, "breast cancer SPE")
download_verified(MEL_URL, MEL_DEST, MEL_MD5, "melanoma h5ad (SIMVI Zenodo 14708000)")

cat("\nData ready. Both raw inputs are in place.\n")
